version: '3.8'

services:
  web:
   build: ./services/web
   image: rakawbw/neo4j-kafka:latest

  postgres:
    image: debezium/postgres:13
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - PGPASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql

  zookeeper01:
    image: bitnami/zookeeper:latest
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    environment:
        - ZOO_SERVER_ID=101
        - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
        - "2181:2181"

  kafka01:
    depends_on:
        - zookeeper01
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka01
    environment:
        - KAFKA_BROKER_ID=201
        - ALLOW_PLAINTEXT_LISTENER=true
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka01:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181
    ports:
        - "9092:9092"

  kafcon:
    depends_on:
        - kafka01
    image: confluentinc/cp-kafka-connect
    container_name: connect
    hostname: kafcon
    environment:
        - CONNECT_BOOTSTRAP_SERVERS=kafka01:9092
        - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_GROUP_ID=kafcon
        - CONNECT_CONFIG_STORAGE_TOPIC=kafcon_config
        - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
        - CONNECT_OFFSET_STORAGE_TOPIC=kafcon_offset
        - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
        - CONNECT_STATUS_STORAGE_TOPIC=kafcon_status
        - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
        - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
        - CONNECT_REST_ADVERTISED_HOST_NAME=kafcon
        - CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components
    ports:
        - "8083:8083"
    command:
        - bash
        - -c
        - |
          echo "Installing connector plugins"
          confluent-hub install --no-prompt neo4j/kafka-connect-neo4j:5.0.0
          confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.3.2
          confluent-hub install --no-prompt debezium/debezium-connector-postgresql:latest
          /etc/confluent/docker/run &
          sleep infinity

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
        - "8080:8080"
    restart: always
    environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092
        - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=first
        - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://kafcon:8083
  services:
  neo4j:
    image: neo4j:5.2.0-enterprise
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_bolt_advertised__address: :7687
      NEO4JLABS_PLUGINS: '["apoc"]'
